

SECTOR_MAPPING_YAHOO_TO_GICS = {
    "Basic Materials": "Materials",
    "Communication Services": "Communication Services",
    "Consumer Cyclical": "Consumer Discretionary",
    "Consumer Defensive": "Consumer Staples",
    "Energy": "Energy",
    "Financial Services": "Financials",
    "Healthcare": "Health Care",
    "Industrials": "Industrials",
    "Real Estate": "Real Estate",
    "Technology": "Information Technology",
    "Utilities": "Utilities"
}

INDUSTRY_MAPPING_YAHOO_TO_GICS = {
    "Advertising Agencies": "Media & Entertainment",
    "Aerospace & Defense": "Aerospace & Defense",
    "Agricultural Inputs": "Chemicals",
    "Airlines": "Airlines",
    "Apparel Manufacturing": "Textiles, Apparel & Luxury Goods",
    "Asset Management": "Capital Markets",
    "Auto Manufacturers": "Automobiles",
    "Auto Parts": "Auto Components",
    "Banks - Diversified": "Banks",
    "Banks - Regional": "Banks",
    "Beverages - Brewers": "Beverages",
    "Beverages - Non-Alcoholic": "Beverages",
    "Beverages - Wineries & Distilleries": "Beverages",
    "Biotechnology": "Biotechnology",
    "Broadcasting": "Media & Entertainment",
    "Building Materials": "Construction Materials",
    "Business Equipment & Supplies": "Industrial Conglomerates",
    "Capital Markets": "Capital Markets",
    "Chemicals": "Chemicals",
    "Communication Equipment": "Communications Equipment",
    "Consulting Services": "Professional Services",
    "Consumer Electronics": "Technology Hardware, Storage & Peripherals",
    "Credit Services": "Consumer Finance",
    "Department Stores": "Multiline Retail",
    "Diagnostics & Research": "Life Sciences Tools & Services",
    "Discount Stores": "Multiline Retail",
    "Drug Manufacturers - General": "Pharmaceuticals",
    "Education & Training Services": "Diversified Consumer Services",
    "Electrical Equipment & Parts": "Electrical Equipment",
    "Electronic Components": "Electronic Equipment, Instruments & Components",
    "Electronic Gaming & Multimedia": "Interactive Media & Services",
    "Engineering & Construction": "Construction & Engineering",
    "Entertainment": "Entertainment",
    "Farm & Heavy Construction Machinery": "Machinery",
    "Financial Data & Stock Exchanges": "Capital Markets",
    "Food Distribution": "Food & Staples Retailing",
    "Footwear & Accessories": "Textiles, Apparel & Luxury Goods",
    "Furnishings, Fixtures & Appliances": "Household Durables",
    "Gold": "Metals & Mining",
    "Grocery Stores": "Food & Staples Retailing",
    "Health Information Services": "Health Care Technology",
    "Health Care Plans": "Health Care Providers & Services",
    "Home Improvement Retail": "Specialty Retail",
    "Industrial Distribution": "Trading Companies & Distributors",
    "Information Technology Services": "IT Services",
    "Infrastructure Operations": "Diversified Telecommunication Services",
    "Insurance Brokers": "Insurance",
    "Integrated Freight & Logistics": "Air Freight & Logistics",
    "Internet Content & Information": "Interactive Media & Services",
    "Leisure": "Hotels, Restaurants & Leisure",
    "Lumber & Wood Production": "Paper & Forest Products",
    "Medical Devices": "Health Care Equipment & Supplies",
    "Oil & Gas E&P": "Oil, Gas & Consumable Fuels",
    "Oil & Gas Integrated": "Oil, Gas & Consumable Fuels",
    "Oil & Gas Midstream": "Oil, Gas & Consumable Fuels",
    "Oil & Gas Refining & Marketing": "Oil, Gas & Consumable Fuels",
    "Packaging & Containers": "Containers & Packaging",
    "Personal Services": "Diversified Consumer Services",
    "Pharmaceuticals": "Pharmaceuticals",
    "Real Estate - Development": "Real Estate Management & Development",
    "Real Estate - Diversified": "Equity Real Estate Investment Trusts (REITs)",
    "Recreational Vehicles": "Leisure Products",
    "Renewable Energy": "Electric Utilities",
    "Restaurants": "Hotels, Restaurants & Leisure",
    "Scientific & Technical Instruments": "Life Sciences Tools & Services",
    "Semiconductor Equipment & Materials": "Semiconductors & Semiconductor Equipment",
    "Semiconductors": "Semiconductors & Semiconductor Equipment",
    "Software - Application": "Software",
    "Software - Infrastructure": "Software",
    "Solar": "Electric Utilities",
    "Specialty Retail": "Specialty Retail",
    "Telecom Services": "Diversified Telecommunication Services",
    "Tobacco": "Tobacco",
    "Travel Services": "Hotels, Restaurants & Leisure",
    "Utilities - Regulated Electric": "Electric Utilities",
    "Utilities - Renewable": "Independent Power and Renewable Electricity Producers"
}